### ISSUE TITLE
error logging for cluster jobs

### ISSUE THREAD

**Issue by aednv** [idanefroni/Conservatory#1]
Hi Idan,
Feel free to ignore this idea, but I noticed that when I run processConservation & processGenomes as cluster jobs all of the output from the secondary scripts disappears, and is not visible in the .out or .err file. Would it be possible to add an error log for when secondary scripts are called? (for example, for line 160 in ProcessConservation?) It would also be great if the --verbose parameter could be passed to all the secondary scripts.
Best,
Amber

**Comment by idanefroni** [comment]
Hi Amber,

I see your point, but the reason for this is that that it is multitheaded and the output of all threads will clash in the log file. alternatively, there can be a log file for each thread, but this will generate a large number of logs with the assignments of genes to threads is arbitrary...
We can think of a solution for that, but as it is not a simple fix, it's not a priority.

Idan

On 20/04/2022 20:09:00, Amber de Neve ***@***.***> wrote:
Hi Idan,
Feel free to ignore this idea, but I noticed that when I run processConservation & processGenomes as cluster jobs all of the output from the secondary scripts disappears, and is not visible in the .out or .err file. Would it be possible to add an error log for when secondary scripts are called? (for example, for line 160 in ProcessConservation?) It would also be great if the --verbose parameter could be passed to all the secondary scripts.
Best,
Amber

**Comment by aednv** [comment]
I see- no problem!
Amber
