### ISSUE TITLE
[Very minor issue] Conservatory directory structure is corrupt

### ISSUE THREAD

**Issue by eggrandio** [idanefroni/Conservatory#3]
Hello,

I am trying to run the processGenomes script but I get the following error:

"Conservatory directory structure at (...) is corrupt" where (...) is the directory where I have cloned Conservatory.

Looking at processGenomes code (line 62):

die "ERROR: Conservatory directory structure at ($conservatoryDir) is corrupt\n" unless (-e "$conservatoryDir/genomes" && -e "$conservatoryDir/genomes/blastdb/" && -e "$conservatoryDir/scripts" && -e "$conservatoryDir/alignments");

In the repository, the blastdb directory does not exist. I just created it manually and I could run processGenomes.

I would suggest to either include the directory in the repository or making the error message more explicit.

**Comment by idanefroni** [comment]
Very well, thank you!

The genome directory is still uploading. I'll send you the link once it's done.

On 27/10/2022 16:03:33, Eduardo Gonzalez Grandio ***@***.***> wrote:
Hello,
I am trying to run the processGenomes script but I get the following error:
"Conservatory directory structure at (...) is corrupt" where (...) is the directory where I have cloned Conservatory.
Looking at processGenomes code (line 62):
die "ERROR: Conservatory directory structure at ($conservatoryDir) is corrupt\n" unless (-e "$conservatoryDir/genomes" && -e "$conservatoryDir/genomes/blastdb/" && -e "$conservatoryDir/scripts" && -e "$conservatoryDir/alignments");
In the repository, the blastdb directory does not exist. I just created it manually and I could run processGenomes.
I would suggest to either include the directory in the repository or making the error message more explicit.
