### ISSUE TITLE
Phylogenetic tree construction

### ISSUE THREAD

**Issue by Averstic** [idanefroni/Conservatory#5]
Hi, 

I was wondering if you have any recommendations or guidelines on how to exactly generate a phylogenetic tree for use in conservatory analysis?

**Comment by idanefroni** [comment]
Sure, but can you be more specific? 

In general, you can use ortholog protein alignment and RAxML (or iq-tree2) for the structure and branch lengths of the tree. 

The model is then determined by phyloFit using an alignment of the fourfold degenerate 3rd codon - this is performed using the buildModel script which identifies orthologs and extracts the variant sites that are informative (found in the scripts directory).
We also tried building the tree using the fourfold degenerate site alignments (produced by buildModel) and it seems to be better than protein tress in term of branch lengths assignments.

Hope that helps
